classDiagram
	class MaterialProperties {
		shore_hardneess
		nozzle_print_temperature
	}
	class MaterialType {

	}
	class Material {
		properties: MaterialProperties
		type: MaterialType
		brand
		name
		abbreviation
		primary_color
	}
	MaterialType --> Material
	MaterialProperties --> Material

	class MaterialContainer {
		inner_diameter
		outer_diameter
		width
		empty_weight
	}

	class MaterialPackage {
		material: Material
		container: MaterialContainer
		gtin
		filament_diameter
		nominal_full_weight
	}
	Material --> MaterialPackage
	MaterialContainer --> MaterialPackage

	class DynamicData {
		consumed_weight
	}
	class MaterialPackageInstance {
		package: MaterialPackage
		dynamic_data: DynamicData
		actual_full_length
	}
	MaterialPackage --> MaterialPackageInstance
	DynamicData --> MaterialPackageInstance
